### ISSUE TITLE
Fail to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by cibersheep** [beebem-unix/beebem#4]
Hello. I tried to build the emulator following the instructions for a user on the readme.

```
-- Found Threads: TRUE  
-- Found SDL: /usr/lib/x86_64-linux-gnu/libSDLmain.a;/usr/lib/x86_64-linux-gnu/libSDL.so;-lpthread (found version "1.2.15") 
-- Found GTK2_GTK: /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so  
-- found GTK2 version 2.24.32
-- Configuring done
-- Generating done
-- Build files have been written to: /home/[...]/beebem/_build
[...]$ make
Scanning dependencies of target eg
[  1%] Building C object src/gui/CMakeFiles/eg.dir/sdl.c.o
In file included from /home/[...]/beebem/src/gui/sdl.c:6:
/[...]/beebem/src/gui/sdl.h:10:10: fatal error: SDL.h: El fitxer o directori no existeix
   10 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [src/gui/CMakeFiles/eg.dir/build.make:63: src/gui/CMakeFiles/eg.dir/sdl.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:183: src/gui/CMakeFiles/eg.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

Adding `-I/usr/include/SDL` to the cmake helps detect SDL libs.
as `add_definitions(-DWITH_UNIX_EXTRAS=1 -I/usr/include/SDL -DREG_FILENAME="beebem.registry")`

it builds but fails linking the libs:
```
[100%] Linking CXX executable beebem
/usr/bin/ld: CMakeFiles/beebem.dir/main.cpp.o: in function `main':
main.cpp:(.text+0x19d): undefined reference to `SDL_GetTicks'
/usr/bin/ld: main.cpp:(.text+0x343): undefined reference to `SDL_ShowCursor'
```

full log: https://paste.ubuntu.com/p/NKZk9JrbPf/

Is there a lib I miss?

**Comment by dmah42** [comment]
hello.. in the CMakeLists we required SDL (https://github.com/beebem-unix/beebem/blob/main/CMakeLists.txt#L30) and in the src folder we link to it (https://github.com/beebem-unix/beebem/blob/main/src/CMakeLists.txt#L23).  this should be enough.

i see in your log that your system is finding libSDL and that should be enough, but i agree that it looks like while it's finding libSDL it somehow isn't passing those through to the build correctly.  maybe that line from src/CMakeLists.txt also needs to be added to src/gui/CMakelists.txt (here https://github.com/beebem-unix/beebem/blob/main/src/gui/CMakeLists.txt#L18).

i'm curious why i'm not seeing this issue though.

**Comment by cibersheep** [comment]
Mmmhm... the only weird thing I did was requiring an older version of cmake. That might be it ¬¬ sorry I forgot to mention

**Comment by dmah42** [comment]
i can't immediately see why that would cause an issue.. have you tried since with a newer version?

**Comment by cibersheep** [comment]
Hmm... it was easier than I thought to get a more current version.
Aand... yep, it builds. Sorry for that.

**Comment by youngervenus** [comment]
I am having a very similar issue.
originaly I got this responce:

```\[helioscultist@phylactery \_build\]$ cmake ..
-- disabling debugger
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:227 (message):
  Could NOT find SDL (missing: SDL\_LIBRARY SDL\_INCLUDE\_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:591 (\_FPHSA\_FAILURE\_MESSAGE)
  /usr/share/cmake/Modules/FindSDL.cmake:227 (find\_package\_handle\_standard\_args)
  CMakeLists.txt:30 (find\_package)
```

as trying the flag got me:

```[helioscultist@phylactery _build]$ cmake -DBEEBEM_ENABLE_ECONET ..
CMake Error: Parse error in command line argument: BEEBEM_ENABLE_ECONET
 Should be: VAR:type=value

CMake Error: Run 'cmake --help' for all supported options.
```

looking into the CMakeList.txt I saw that it was "on", so I figured it would be fine to neglect.

(as an aside the releases zip doesn't have the CMakeLists.txt ... Yeah I don't get it)

Now noticing that my systems SDL is called sld3 i went into the CMakeLists.txt and changed SDL to SLD 3. (line 30). This caused cmake to proceed.
Now trying make, fails, perhaps not unexpectedly.

However here is the funny bit, it fails in the very manner as the OP.

And now I don't quite know what to do.

I am using arch updated as of today.
